# Generated by Django 4.1.7 on 2023-04-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_owner', models.CharField(max_length=254)),
                ('listing_name', models.CharField(max_length=254)),
                ('listing_image_url', models.CharField(max_length=254)),
                ('listing_cloudfront_url', models.CharField(max_length=254)),
                ('listing_description', models.CharField(max_length=254)),
                ('listing_unit_price', models.FloatField()),
                ('listing_max_quantity', models.PositiveIntegerField()),
                ('listing_remaining_quantity', models.PositiveIntegerField()),
                ('listing_end_date', models.DateField()),
                ('listing_delivery_date', models.DateField()),
                ('listing_status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('order_placed', 'order_placed'), ('order_received', 'order_received'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], max_length=254)),
                ('listing_created_at', models.DateTimeField(auto_now_add=True)),
                ('listing_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_owner', models.CharField(max_length=254)),
                ('order_listing_id', models.IntegerField()),
                ('order_quantity', models.PositiveIntegerField()),
                ('order_unit_price', models.FloatField()),
                ('order_total_amount', models.FloatField()),
                ('order_contact_details', models.CharField(max_length=254)),
                ('order_address', models.CharField(max_length=254)),
                ('order_postal_code', models.CharField(max_length=254)),
                ('order_status', models.CharField(choices=[('placed', 'placed'), ('closed', 'closed'), ('order_placed', 'order_placed'), ('order_received', 'order_received'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('seller_cancelled', 'seller_cancelled')], max_length=254)),
                ('order_created_at', models.DateTimeField(auto_now_add=True)),
                ('order_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
        ),
    ]
